# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMob Banner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdMob Banner

pod 'Google-Mobile-Ads-SDK'

end
